### ISSUE TITLE
Error during ellipse calculation when a vowel has only 1 token

### ISSUE THREAD

**Issue by jmriebold** [drammock/phonR#34]
When one of the vowels being plotted has only a single token, plotting with `ellipse.line = T` yields `Error in es$vec %*% diag(sqrt(es$val)) : non-conformable arguments`. This makes sense of course, but I'm not sure what the correct behavior should be. Maybe just ignore calculation of an ellipse for that vowel?

**Comment by drammock** [comment]
thanks, should be fixed now. Let me know if it still errors with your data.
