### ISSUE TITLE
legend and color order don't match

### ISSUE THREAD

**Issue by valerief** [drammock/phonR#37]
I think the labels in the legend are printed in the order they appear in the data set, but the colors are applied and shown in the order of the levels of the labels.  In the example below, things would all match if the labels were listed in the order of the levels: 
Levels: AA AE AO EY IY OW UW

> head(outer$vowel_label)
[1] AO EY IY AA OW EY
Levels: AA AE AO EY IY OW UW
plotVowels(f1=outer$nry2_vowel_f1_pt50, f2=outer$nry2_vowel_f2_pt50, vowel=outer$vowel_label, 
           group=outer$stress, 
           plot.tokens=F, 
           plot.means=T, pch.means=outer$vowel_label, #cex.means=2,
           poly.line=T, poly.fill=F, 
           poly.order=c("IY", "EY", "AE", "AA", "AO", "OW", "UW", "UH", "AH", "EH", "IH"), 
           var.col.by=outer$vowel_label, var.style.by=NULL, 
           legend.kwd="bottomleft", 
           ylim=c(-0.2,-1.0), xlim=c(1.02,0.2), 
           pretty = T)
![vowelcolors](https://cloud.githubusercontent.com/assets/6989089/7211353/ded6a3b8-e50e-11e4-8b34-15f4c7b41812.jpeg)

**Comment by drammock** [comment]
This was noticed by another user several weeks ago and should have already
been fixed. Please try updating phonR using
devtools::install_github("drammock/phonR") and see if the problem persists.

**Comment by valerief** [comment]
Oops, sorry I didn't see that!

**Comment by drammock** [comment]
No problem, I didn't announce it and there was no official issue created so
it would have been hard to discover. Please do test with the current code,
and close this issue if the problem goes away.
