### ISSUE TITLE
poly.args lty not working

### ISSUE THREAD

**Issue by valerief** [drammock/phonR#39]
Hi Dan, 
I'm trying to set the line types for polygon lines for B&W plots, so that I can cross black/gray with solid/dashed for 4 line color-type combos.  When I var.style.by to the same vector as var.col.by, there are as many line types as factor levels.  I tried adding poly.args=list(lty=c("dashed", "solid", "dashed", "solid"), but then all the line types print as the first type in the list (eg all dashed), while the lines in the legend show the full cycle of types in the default order (solid, dashed, dotted).  I'm using phonR-1.0-3.R from mid-April. Sample:

title <- "Vowel space by stance strength"
subtitle <- "stressed-content vowels" 
with(str_data, plotVowels(f1=nry2_vowel_f1_pt50, f2=nry2_vowel_f2_pt50, vowel=ipa, 
                          group=coarse_strength, 
                          var.col.by=coarse_strength, var.style.by=coarse_strength, 
                          col=c("gray65", "gray50", "gray25", "black"), poly.args=list(lwd=2), 
                          plot.tokens=F, plot.means=T, pch.means=ipa, cex.means=1.25,
                          poly.line=T, poly.fill=F, poly.order=c("i", "\U026A", "e", "\U025B", "\U00E6", "\U0251",  "\U0254", "\U0254\U0279", "o", "\U028A", "u"), 
                          legend.kwd="bottomleft", legend.args=list(lwd=2),
                          xlim=c(1.05,0), ylim=c(-0.1,-1.1),  
                          pretty = T, main = title, sub = subtitle, cex.main=1.2, cex.sub=0.9 ))

**Comment by drammock** [comment]
In future, it is much easier for me if your sample code uses the `indo` data included with phonR, or if you include your data (or a subset of it) in the code you provide using `dput()`.  

I think this is actually a bug... let me confirm that I actually understand what you want first. You have data with 4 groups, you're plotting the mean for each group, you have 4 specific colors you want to use (1 for each group) and 2 specific linetypes you want to use ("solid" and "dashed") that should get recycled, so you would end up with:

- group 1: "gray65", "solid"
- group 2: "gray50", "dashed"
- group 3: "gray25", "solid"
- group 4: "black", "dashed"

I confirm that if you provide `col=c("gray65", "gray50", "gray25", "black")` and `lty=c("solid", "dashed")` it will fail; the `lty` is failing to get recycled internally, so the other groups are getting `lty=NA`.

I confirm that if you provide `col=c("gray65", "gray50", "gray25", "black")` and `lty=c("solid", "dashed", "solid", "dashed")` the plot will get drawn, but the specified line types aren't actually getting used (either for the plot or the legend).

here (for later reference) I'm trying to reproduce what you want with the sample data:

```r
library(phonR)
packageVersion("phonR")  # 1.0.3
data(indoVowels)
mydata <- indo[indo$gender %in% "f",]  # subset so we have only 4 individuals

with(mydata, plotVowels(f1, f2, vowel, group=subj, var.col.by=subj, var.style.by=subj, plot.tokens=FALSE, plot.means=TRUE, pch.means=vowel, poly.line=TRUE, poly.order=c("i", "e", "a", "o", "u"), legend.kwd="bottomleft", legend.args=list(lwd=2), pretty=TRUE, main="foo", sub="bar", col=c("gray65", "gray50", "gray25", "black"), lty=c("solid", "dashed")))
## raises the following error:
## Error in plot.xy(xy, type, ...) : invalid hex digit in 'color' or 'lty'
```

Will look into this and see what I can do. In the meantime, if I've mis-interpreted what it is you want, please let me know.

**Comment by drammock** [comment]
confirmed that wrapping `lty=c(...)` in `poly.args=list(lty=c(...))` does not work either.

**Comment by drammock** [comment]
OK, this should work now:

```r
devtools::install_github("drammock/phonR")
library(phonR)
packageVersion("phonR")  # should now say 1.0.4
mydata <- indo[indo$gender %in% "f",]  # subset so we have only 4 individuals
with(mydata, plotVowels(f1, f2, vowel, group=subj, var.col.by=subj, var.style.by=subj,
     plot.tokens=FALSE, plot.means=TRUE, pch.means=vowel, poly.line=TRUE, 
     poly.order=c("i", "e", "a", "o", "u"), legend.kwd="bottomleft", 
     legend.args=list(lwd=2, seg.len=4), pretty=TRUE, main="foo", sub="bar", 
     col=c("gray65", "gray50", "gray25", "black"), lty=c("solid", "dashed")))
```
Here is what I get:
![fixed](https://cloud.githubusercontent.com/assets/1810515/8031501/452df344-0e01-11e5-8ffe-de7690c43169.png)

**Comment by drammock** [comment]
argh. although it will work for your particular use case in its current state, I broke some other stuff.  Stand by.

**Comment by drammock** [comment]
OK, I am pretty sure it's all fixed now.  The following should work:

```r
devtools::install_github("drammock/phonR")
library(phonR)
packageVersion("phonR")  # 1.0.4
data(indoVowels)
mydata <- indo[indo$gender %in% "f",]  # subset so we have only 4 individuals
with(mydata, plotVowels(f1, f2, vowel, group=subj, var.col.by=subj, 
                        var.style.by=subj, plot.tokens=FALSE, plot.means=TRUE, 
                        pch.means=vowel, pretty=TRUE, main="foo", sub="bar", 
                        poly.line=TRUE, poly.order=c("i", "e", "a", "o", "u"), 
                        legend.kwd="bottomleft", legend.args=list(lwd=2, seg.len=4), 
                        col=c("gray65", "gray50", "gray25", "black"),
                        lty=c("solid", "dashed")))
```
![fixed1](https://cloud.githubusercontent.com/assets/1810515/8057385/79f0006c-0ee3-11e5-87a4-79bf10c72c1f.png)

This should also work, sort of:
```r
with(mydata, plotVowels(f1, f2, vowel, group=subj, var.col.by=subj, 
                        var.style.by=subj, plot.tokens=FALSE, plot.means=TRUE, 
                        pch.means=vowel, pretty=TRUE, main="foo", sub="bar", 
                        poly.line=TRUE, poly.order=c("i", "e", "a", "o", "u"), 
                        legend.kwd="bottomleft", legend.args=list(lwd=2, seg.len=4), 
                        poly.args=list(border=c("gray65", "gray50", "gray25", "black"),
                                       lty=c("solid", "dashed"))))
```
![fixed2](https://cloud.githubusercontent.com/assets/1810515/8057394/84b5c478-0ee3-11e5-8d8b-418f9da3b717.png)

Notice that if you specify the polygon color via `poly.args` then the correct keyword is `border` and not `col`. Notice also how that affects only the polygon itself and not the plotted means, and how I couldn't get the legend to follow the color specified in `poly.args=list(border...)` without messing up legend handling for more basic types of plots.  Regardless, I'll consider this "fixed" for now given that it works to specify `col` and `lty` directly.
