### ISSUE TITLE
axis values and labels overlap when sizes are adjusted

### ISSUE THREAD

**Issue by jonorthwash** [drammock/phonR#45]
In the following excerpts, I'm using `cex.axis=2, cex.lab=3` within `plotVowels()`.  The original positions appear to be kept, so the increased sizes of the two sets of text leads to them overlapping.

![2018-08-18_001](https://user-images.githubusercontent.com/963849/44303253-e792f080-a309-11e8-8f1f-d107a7b7d52f.png)
![2018-08-18_002](https://user-images.githubusercontent.com/963849/44303254-e792f080-a309-11e8-986a-86874bc0a8be.png)

**Comment by drammock** [comment]
working on a fix, but in the meantime you can pass `xlab="", ylab=""` and then add the axis labels using `mtext(..., line=some_suitably_large_number)`
